### ISSUE TITLE
Doesn't work in groups with topics 

### ISSUE THREAD

**Issue by luccascomvoce** [AmanoTeam/UnuRobot#12]
Bot does not respond in groups with topics. I created a topic for games in my group, but @unurobot doesn't respond. Other game bots work correctly

**Comment by alissonlauffer** [comment]
hm, that's weird. I have implemented topics support already (and just tested in a group). Can you try giving admin rights to the bot (can be just admin title, no permissions are required)?

**Comment by luccascomvoce** [comment]
> hm, that's weird. I have implemented topics support already (and just tested in a group). Can you try giving admin rights to the bot (can be just admin title, no permissions are required)?

True. Making the bot admin without permissions didn't solve it. But when giving permission to manage topics it started to work. Thanks! The bot needs to have permission to manage topics.
